# Build Step
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

# To prevent husky from being executed in production
ENV HUSKY=0

RUN npm ci

COPY . .

RUN npm run build

# Production Step
FROM node:22-alpine

WORKDIR /app

# Copy only files needed
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/package*.json ./

# To prevent husky from being executed in production
ENV HUSKY=0

RUN npm ci --only=production

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
